version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - .:/app
    ports:
      - '9200:9200'
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    env_file:
      - '.env'

  redis:
    image: 'redis:3.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'redis'
      - elasticsearch
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: sidekiq
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
  elasticsearch: