version: '2'

services:
  redis:
    image: 'redis:3.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: sidekiq
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
